# Generated by Django 6.1.1 on 2026-09-11 13:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='pocket', max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('decision', models.CharField(choices=[('stored', 'Stored'), ('updated', 'Updated'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('ignored', 'Ignored'), ('rejected', 'Rejected')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='pocket', max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('segments', models.JSONField()),
                ('text', models.TextField()),
                ('captured_at', models.DateTimeField()),
                ('revisions', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('hints', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('inbox', 'Waiting to be processed'), ('processed', 'Processed into entries'), ('dismissed', 'Dismissed, nothing worth keeping')], default='inbox', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('memory', 'Memory'), ('thought', 'Thought'), ('decision', 'Decision'), ('reminder', 'Reminder'), ('digest', 'Digest')], max_length=16)),
                ('raw_text', models.TextField()),
                ('claim', models.CharField(max_length=280)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('happened_precision', models.CharField(blank=True, choices=[('exact', 'Exact time'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('covers_from', models.DateTimeField(blank=True, null=True)),
                ('covers_to', models.DateTimeField(blank=True, null=True)),
                ('supersede_reason', models.CharField(blank=True, choices=[('correction', 'Correction: the old entry was never true'), ('change', 'Change: the old entry was true until this happened')], max_length=16)),
                ('external_ref', models.CharField(blank=True, max_length=128)),
                ('client_name', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('claim', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('raw_text', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='memories.capture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(related_name='cited_by', through='memories.Citation', to='memories.entry')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='memories.entry')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.AddField(
            model_name='citation',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='memories.entry'),
        ),
        migrations.AddField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='memories.entry'),
        ),
        migrations.CreateModel(
            name='PocketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_user_id', models.CharField(max_length=128, unique=True)),
                ('speaker_label', models.CharField(help_text="Your name as Pocket's voice print labels you.", max_length=128)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pocket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('object_type', models.CharField(max_length=16)),
                ('external_ref', models.CharField(blank=True, max_length=160)),
                ('forgotten_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tombstones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['owner', 'status', '-captured_at'], name='capture_inbox'),
        ),
        migrations.AddConstraint(
            model_name='capture',
            constraint=models.UniqueConstraint(fields=('owner', 'source', 'external_id'), name='unique_capture_per_source'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='entry_search_gin'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='entry_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['owner', '-happened_at'], name='entry_owner_happened'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['owner', '-recorded_at'], name='entry_owner_recorded'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(condition=models.Q(('completed_at__isnull', True), ('kind', 'reminder')), fields=['due_at'], name='entry_open_reminders'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_at__isnull', False), ('kind', 'reminder')), models.Q(models.Q(('kind', 'reminder'), _negated=True), ('due_at__isnull', True)), _connector='OR'), name='due_at_iff_reminder'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'digest'), _negated=True), models.Q(('covers_from__isnull', False), ('covers_from__lte', models.F('covers_to')), ('covers_to__isnull', False)), _connector='OR'), name='digest_has_window'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('happened_at__isnull', True), ('happened_precision', '')), models.Q(('happened_at__isnull', False), models.Q(('happened_precision', ''), _negated=True)), _connector='OR'), name='precision_iff_happened_at'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes', models.F('id')), _negated=True), name='cannot_supersede_self'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supersede_reason', ''), ('supersedes__isnull', True)), models.Q(('supersedes__isnull', False), models.Q(('supersede_reason', ''), _negated=True)), _connector='OR'), name='reason_iff_supersedes'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supersede_reason', 'change'), _negated=True), ('happened_at__isnull', False), _connector='OR'), name='change_says_when'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('happened_at__isnull', True), ('valid_until__gte', models.F('happened_at')), _connector='OR'), name='valid_until_after_happened'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('capture__isnull', False), ('kind', 'digest'), _negated=True), name='digests_have_no_capture'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('owner', 'external_ref'), name='unique_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(fields=('digest', 'source'), name='unique_citation'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('digest', models.F('source')), _negated=True), name='no_self_citation'),
        ),
        migrations.AddIndex(
            model_name='tombstone',
            index=models.Index(fields=['owner', 'external_ref'], name='tombstone_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='tombstone',
            constraint=models.UniqueConstraint(fields=('owner', 'object_id'), name='one_tombstone_per_object'),
        ),
    ]
