# Generated by Django 6.1.1 on 2026-09-24 13:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import memories.models


class Migration(migrations.Migration):
    dependencies = [
        ("memories", "0002_immutability_triggers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("token_prefix", models.CharField(editable=False, max_length=12)),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("memento:read", "Read entries and the inbox"),
                                ("memento:write", "Save entries and close captures"),
                                ("memento:forget", "Permanently delete"),
                            ],
                            max_length=32,
                        ),
                        default=memories.models.default_scopes,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("direct", "Direct: the client structures its own entries"),
                            (
                                "inbox",
                                "Inbox: every save goes to the inbox for the distiller (M3)",
                            ),
                        ],
                        default="direct",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "name"), name="unique_client_name")
                ],
            },
        ),
    ]
