# Generated by Django 6.1.1 on 2026-09-24 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memories", "0005_profile_timezone_from_pocket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pocketlink",
            name="timezone",
        ),
    ]
