# Generated by Django 6.1.1 on 2026-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0006_remove_pocketlink_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="pocketlink",
            name="one_unnamed_speaker_is_me",
            field=models.BooleanField(
                default=False,
                help_text="Keep recordings with exactly one speaker whom Pocket hasn't named (SPEAKER_00). You wear the Pocket, so that is almost always you; anything else you can forget. Two or more speakers, or someone Pocket has named, are still skipped.",
            ),
        ),
    ]
