# Generated by Django 6.1.1 on 2026-09-27 11:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0008_pocketlink_one_speaker_is_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=512, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=128)),
                ('redirect_uris', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512))),
                ('secret_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('secret_expires_at', models.DateTimeField(blank=True, null=True)),
                ('from_metadata_document', models.BooleanField(default=False)),
                ('metadata_fresh_until', models.DateTimeField(blank=True, null=True)),
                ('client_uri', models.CharField(blank=True, max_length=512)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=512)),
                ('code_challenge', models.CharField(max_length=128)),
                ('code_challenge_method', models.CharField(default='S256', max_length=8)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('memento:read', 'Read entries and the inbox'), ('memento:write', 'Save entries and close captures'), ('memento:forget', 'Permanently delete')], max_length=32))),
                ('resource', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='memories.client')),
                ('oauth_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='memories.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('use', models.CharField(choices=[('access', 'Access token'), ('refresh', 'Refresh token')], max_length=8)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('memento:read', 'Read entries and the inbox'), ('memento:write', 'Save entries and close captures'), ('memento:forget', 'Permanently delete')], max_length=32))),
                ('resource', models.CharField(blank=True, max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='memories.client')),
                ('oauth_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='memories.oauthclient')),
            ],
            options={
                'indexes': [models.Index(fields=['use', 'expires_at'], name='memories_oa_use_e61005_idx')],
            },
        ),
    ]
