# Generated by Django 6.1.1 on 2026-09-27 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0010_client_oauth_client_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='family',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['family'], name='memories_oa_family_d02e42_idx'),
        ),
    ]
