# Generated by Django 6.1.1 on 2026-09-27 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0011_oauth_token_family"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pocketlink",
            name="pocket_user_id",
            field=models.CharField(
                blank=True,
                help_text="Leave blank: it is filled in from Pocket's first delivery. Only needed if Memento ever has more than one Pocket link.",
                max_length=128,
            ),
        ),
        migrations.AddConstraint(
            model_name="pocketlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pocket_user_id", ""), _negated=True),
                fields=("pocket_user_id",),
                name="pocketlink_user_id_unique_when_set",
            ),
        ),
    ]
